//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_NotesDeFrais.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpanseTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpanseTypes()
        {
            this.Expanses = new HashSet<Expanses>();
        }
    
        public System.Guid ExpenseType_ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Ceiling { get; set; }
        public bool Fixed { get; set; }
        public bool OnlyManagers { get; set; }
        public System.Guid Tva_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expanses> Expanses { get; set; }
        public virtual Tvas Tvas { get; set; }
    }
}
