//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_NotesDeFrais.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expanses
    {
        public System.Guid Expanse_ID { get; set; }
        public System.Guid ExpanseReport_ID { get; set; }
        public int Day { get; set; }
        public System.Guid ExpanseType_ID { get; set; }
        public System.Guid Customer_ID { get; set; }
        public System.Guid Project_ID { get; set; }
        public double Amount_HT { get; set; }
        public double Amount_TVA { get; set; }
        public double Amount_TTC { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ExpanseReports ExpanseReports { get; set; }
        public virtual ExpanseTypes ExpanseTypes { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
