//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_NotesDeFrais.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpanseReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpanseReports()
        {
            this.Expanses = new HashSet<Expanses>();
        }
    
        public System.Guid ExpanseReport_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public System.Guid Author_ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int StatusCode { get; set; }
        public Nullable<System.DateTime> ManagerValidationDate { get; set; }
        public Nullable<System.DateTime> AccountingValidatationDate { get; set; }
        public double Total_HT { get; set; }
        public double Total_TVA { get; set; }
        public double Total_TTC { get; set; }
        public string ManagerComment { get; set; }
        public string AccountingComment { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expanses> Expanses { get; set; }
    }
}
