//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_NotesDeFrais.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotesDeFraisEntities : DbContext
    {
        public NotesDeFraisEntities()
            : base("name=NotesDeFraisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<ExpanseReports> ExpanseReports { get; set; }
        public virtual DbSet<Expanses> Expanses { get; set; }
        public virtual DbSet<ExpanseTypes> ExpanseTypes { get; set; }
        public virtual DbSet<Poles> Poles { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Tvas> Tvas { get; set; }
    }
}
